from app.core.compat import StrEnum


class FileKind(StrEnum):
    IMAGE = "IMAGE"
    DOCUMENT = "DOCUMENT"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    OTHER = "OTHER"


class ScanStatus(StrEnum):
    PENDING = "PENDING"
    CLEAN = "CLEAN"
    INFECTED = "INFECTED"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"


class AttachmentEntityType(StrEnum):
    ASSET = "ASSET"
    ASSET_TRANSFER = "ASSET_TRANSFER"
    MAINTENANCE_REQUEST = "MAINTENANCE_REQUEST"
    MAINTENANCE_WORK_ORDER = "MAINTENANCE_WORK_ORDER"
    MAINTENANCE_FINDING = "MAINTENANCE_FINDING"
    ASSET_FAILURE = "ASSET_FAILURE"


class AttachmentCategory(StrEnum):
    ASSET_PROFILE_PHOTO = "ASSET_PROFILE_PHOTO"
    ASSET_CONDITION_PHOTO = "ASSET_CONDITION_PHOTO"
    NAMEPLATE_PHOTO = "NAMEPLATE_PHOTO"
    SERIAL_NUMBER_PHOTO = "SERIAL_NUMBER_PHOTO"
    QR_RFID_TAG_PHOTO = "QR_RFID_TAG_PHOTO"
    MANUAL_BOOK = "MANUAL_BOOK"
    USER_GUIDE = "USER_GUIDE"
    INSTALLATION_GUIDE = "INSTALLATION_GUIDE"
    MAINTENANCE_MANUAL = "MAINTENANCE_MANUAL"
    TECHNICAL_DRAWING = "TECHNICAL_DRAWING"
    DATASHEET = "DATASHEET"
    WARRANTY_DOCUMENT = "WARRANTY_DOCUMENT"
    INVOICE = "INVOICE"
    CERTIFICATE = "CERTIFICATE"
    HANDOVER_DOCUMENT = "HANDOVER_DOCUMENT"
    MOVEMENT_EVIDENCE = "MOVEMENT_EVIDENCE"
    DAMAGE_PHOTO = "DAMAGE_PHOTO"
    BEFORE_MAINTENANCE_PHOTO = "BEFORE_MAINTENANCE_PHOTO"
    DURING_MAINTENANCE_PHOTO = "DURING_MAINTENANCE_PHOTO"
    AFTER_MAINTENANCE_PHOTO = "AFTER_MAINTENANCE_PHOTO"
    MAINTENANCE_REPORT = "MAINTENANCE_REPORT"
    FINDING_PHOTO = "FINDING_PHOTO"
    FAILURE_PHOTO = "FAILURE_PHOTO"
    ROOT_CAUSE_EVIDENCE = "ROOT_CAUSE_EVIDENCE"
    OTHER = "OTHER"


class AttachmentVisibility(StrEnum):
    INTERNAL = "INTERNAL"
    RESTRICTED = "RESTRICTED"
    VENDOR_SHARED = "VENDOR_SHARED"
    PUBLIC_REFERENCE = "PUBLIC_REFERENCE"


class AttachmentSource(StrEnum):
    UPLOAD = "UPLOAD"
    CAMERA = "CAMERA"
    MOBILE_SCAN = "MOBILE_SCAN"
    SAP_SYNC = "SAP_SYNC"
    SYSTEM_GENERATED = "SYSTEM_GENERATED"

