from enum import StrEnum


class BusinessPartnerRoleType(StrEnum):
    SUPPLIER = "SUPPLIER"
    MANUFACTURER = "MANUFACTURER"
    LESSOR = "LESSOR"
    MAINTENANCE_VENDOR = "MAINTENANCE_VENDOR"
    WARRANTY_PROVIDER = "WARRANTY_PROVIDER"
    INSURER = "INSURER"
    SOFTWARE_PUBLISHER = "SOFTWARE_PUBLISHER"
