from enum import StrEnum


class ScanType(StrEnum):
    VERIFY = "VERIFY"
    DISPATCH = "DISPATCH"
    RECEIVE = "RECEIVE"
    CHECK_IN = "CHECK_IN"
    CHECK_OUT = "CHECK_OUT"
    STOCKTAKE = "STOCKTAKE"
    RFID_GATE_ENTRY = "RFID_GATE_ENTRY"
    RFID_GATE_EXIT = "RFID_GATE_EXIT"
    MAINTENANCE_IN = "MAINTENANCE_IN"
    MAINTENANCE_OUT = "MAINTENANCE_OUT"


class ScanSource(StrEnum):
    MOBILE = "MOBILE"
    WEB = "WEB"
    RFID_GATE = "RFID_GATE"
    API = "API"


class MatchStatus(StrEnum):
    MATCHED = "MATCHED"
    UNKNOWN_TAG = "UNKNOWN_TAG"
    EXPECTED_LOCATION = "EXPECTED_LOCATION"
    UNEXPECTED_LOCATION = "UNEXPECTED_LOCATION"
    DUPLICATE = "DUPLICATE"
    UNAUTHORIZED_MOVEMENT = "UNAUTHORIZED_MOVEMENT"


class ProcessingStatus(StrEnum):
    RECEIVED = "RECEIVED"
    PROCESSED = "PROCESSED"
    REJECTED = "REJECTED"


class VerificationResult(StrEnum):
    PRESENT_MATCH = "PRESENT_MATCH"
    PRESENT_WRONG_LOCATION = "PRESENT_WRONG_LOCATION"
    PRESENT_WRONG_CUSTODIAN = "PRESENT_WRONG_CUSTODIAN"
    TAG_NOT_REGISTERED = "TAG_NOT_REGISTERED"
    ASSET_NOT_EXPECTED = "ASSET_NOT_EXPECTED"
    NOT_FOUND = "NOT_FOUND"


class ResolutionStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    APPROVED = "APPROVED"


class ResolutionAction(StrEnum):
    LINKED_TO_TRANSFER = "LINKED_TO_TRANSFER"
    MARKED_SCAN_ERROR = "MARKED_SCAN_ERROR"
    RETROACTIVE_TRANSFER = "RETROACTIVE_TRANSFER"
    ESCALATED_UNAUTHORIZED_MOVEMENT = "ESCALATED_UNAUTHORIZED_MOVEMENT"
    STOCKTAKE_RECONCILED = "STOCKTAKE_RECONCILED"


class StocktakeScopeType(StrEnum):
    LOCATION = "LOCATION"
    LOCATION_TREE = "LOCATION_TREE"
    CUSTOM = "CUSTOM"


class StocktakeStatus(StrEnum):
    DRAFT = "DRAFT"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    APPROVED = "APPROVED"
    CANCELLED = "CANCELLED"


class StocktakeSnapshotStatus(StrEnum):
    EXPECTED = "EXPECTED"
    EXCLUDED = "EXCLUDED"


class StocktakeResultType(StrEnum):
    FOUND = "FOUND"
    MISSING = "MISSING"
    UNEXPECTED = "UNEXPECTED"
    WRONG_LOCATION = "WRONG_LOCATION"
    DUPLICATE_TAG = "DUPLICATE_TAG"
    UNKNOWN_TAG = "UNKNOWN_TAG"
