from enum import StrEnum


class AppRole(StrEnum):
    SUPERUSER = "SUPERUSER"
    MAINTENANCE_REQUESTER = "MAINTENANCE_REQUESTER"
    MAINTENANCE_PLANNER = "MAINTENANCE_PLANNER"
    MAINTENANCE_SUPERVISOR = "MAINTENANCE_SUPERVISOR"
    MAINTENANCE_TECHNICIAN = "MAINTENANCE_TECHNICIAN"
    MAINTENANCE_INSPECTOR = "MAINTENANCE_INSPECTOR"
    MAINTENANCE_MANAGER = "MAINTENANCE_MANAGER"
    CONTRACT_ADMIN = "CONTRACT_ADMIN"
    SPARE_PART_CONTROLLER = "SPARE_PART_CONTROLLER"
    ASSET_MANAGER = "ASSET_MANAGER"
    AUDITOR = "AUDITOR"


class AppPermission(StrEnum):
    AUTH_MANAGE = "auth:manage"
    ASSET_READ = "asset:read"
    ASSET_WRITE = "asset:write"
    ATTACHMENT_READ = "attachment:read"
    ATTACHMENT_WRITE = "attachment:write"
    MAINTENANCE_READ = "maintenance:read"
    MAINTENANCE_WRITE = "maintenance:write"
    MAINTENANCE_REPORT_READ = "maintenance:report:read"
    PARTNER_READ = "partner:read"
    PARTNER_WRITE = "partner:write"
    TRACKING_READ = "tracking:read"
    TRACKING_WRITE = "tracking:write"
    TRACKING_REPORT_READ = "tracking:report:read"
