from enum import StrEnum


class AppRole(StrEnum):
    SUPERUSER = "SUPERUSER"
    MAINTENANCE_REQUESTER = "MAINTENANCE_REQUESTER"
    MAINTENANCE_PLANNER = "MAINTENANCE_PLANNER"
    MAINTENANCE_SUPERVISOR = "MAINTENANCE_SUPERVISOR"
    MAINTENANCE_TECHNICIAN = "MAINTENANCE_TECHNICIAN"
    MAINTENANCE_INSPECTOR = "MAINTENANCE_INSPECTOR"
    MAINTENANCE_MANAGER = "MAINTENANCE_MANAGER"
    CONTRACT_ADMIN = "CONTRACT_ADMIN"
    SPARE_PART_CONTROLLER = "SPARE_PART_CONTROLLER"
    ASSET_MANAGER = "ASSET_MANAGER"
    AUDITOR = "AUDITOR"


class AppPermission(StrEnum):
    AUTH_MANAGE = "auth:manage"
    MAINTENANCE_READ = "maintenance:read"
    MAINTENANCE_WRITE = "maintenance:write"
    MAINTENANCE_REPORT_READ = "maintenance:report:read"
