from enum import StrEnum


class MaintenanceRequestType(StrEnum):
    CORRECTIVE = "CORRECTIVE"
    BREAKDOWN = "BREAKDOWN"
    EMERGENCY = "EMERGENCY"
    INSPECTION_FOLLOW_UP = "INSPECTION_FOLLOW_UP"
    PART_REPLACEMENT = "PART_REPLACEMENT"
    PERFORMANCE_DEGRADATION = "PERFORMANCE_DEGRADATION"
    SAFETY = "SAFETY"
    CALIBRATION = "CALIBRATION"
    OTHER = "OTHER"


class MaintenanceRequestSourceType(StrEnum):
    MANUAL = "MANUAL"
    MOBILE = "MOBILE"
    SENSOR = "SENSOR"
    INSPECTION = "INSPECTION"
    SYSTEM = "SYSTEM"


class MaintenanceRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    TRIAGE = "TRIAGE"
    WAITING_INFORMATION = "WAITING_INFORMATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONVERTED_TO_WORK_ORDER = "CONVERTED_TO_WORK_ORDER"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class MaintenanceType(StrEnum):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    PREDICTIVE = "PREDICTIVE"
    CONDITION_BASED = "CONDITION_BASED"
    BREAKDOWN = "BREAKDOWN"
    EMERGENCY = "EMERGENCY"
    INSPECTION = "INSPECTION"
    CALIBRATION = "CALIBRATION"
    OVERHAUL = "OVERHAUL"
    IMPROVEMENT = "IMPROVEMENT"


class WorkOrderExecutionMode(StrEnum):
    INTERNAL = "INTERNAL"
    VENDOR = "VENDOR"
    HYBRID = "HYBRID"


class MaintenanceWorkOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    PLANNED = "PLANNED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    WAITING_PART = "WAITING_PART"
    WAITING_VENDOR = "WAITING_VENDOR"
    COMPLETED = "COMPLETED"
    VERIFICATION = "VERIFICATION"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class MaintenanceRequestWorkOrderRelationshipType(StrEnum):
    PRIMARY = "PRIMARY"
    COMBINED = "COMBINED"
    FOLLOW_UP = "FOLLOW_UP"
    DIAGNOSTIC = "DIAGNOSTIC"
    PART_REPLACEMENT = "PART_REPLACEMENT"


class WorkOrderAssignmentRole(StrEnum):
    SUPERVISOR = "SUPERVISOR"
    LEAD_TECHNICIAN = "LEAD_TECHNICIAN"
    TECHNICIAN = "TECHNICIAN"
    INSPECTOR = "INSPECTOR"
    HELPER = "HELPER"


class MaintenanceTeamType(StrEnum):
    MECHANICAL = "MECHANICAL"
    ELECTRICAL = "ELECTRICAL"
    INSTRUMENTATION = "INSTRUMENTATION"
    IT = "IT"
    FACILITY = "FACILITY"
    VEHICLE = "VEHICLE"
    GENERAL = "GENERAL"
    MIXED = "MIXED"


class MaintenanceTeamMemberRole(StrEnum):
    SUPERVISOR = "SUPERVISOR"
    PLANNER = "PLANNER"
    LEAD_TECHNICIAN = "LEAD_TECHNICIAN"
    TECHNICIAN = "TECHNICIAN"
    INSPECTOR = "INSPECTOR"
    HELPER = "HELPER"


class MaintenanceScheduleSource(StrEnum):
    MANUAL = "MANUAL"
    REQUEST = "REQUEST"
    PREVENTIVE_PLAN = "PREVENTIVE_PLAN"
    METER_TRIGGER = "METER_TRIGGER"
    CONDITION_TRIGGER = "CONDITION_TRIGGER"
    VENDOR_VISIT = "VENDOR_VISIT"
    FOLLOW_UP = "FOLLOW_UP"


class MaintenanceScheduleStatus(StrEnum):
    PLANNED = "PLANNED"
    CONFIRMED = "CONFIRMED"
    DISPATCHED = "DISPATCHED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    MISSED = "MISSED"
    POSTPONED = "POSTPONED"
    CANCELLED = "CANCELLED"
