from enum import StrEnum


class MaintenanceRequestType(StrEnum):
    CORRECTIVE = "CORRECTIVE"
    BREAKDOWN = "BREAKDOWN"
    EMERGENCY = "EMERGENCY"
    INSPECTION_FOLLOW_UP = "INSPECTION_FOLLOW_UP"
    PART_REPLACEMENT = "PART_REPLACEMENT"
    PERFORMANCE_DEGRADATION = "PERFORMANCE_DEGRADATION"
    SAFETY = "SAFETY"
    CALIBRATION = "CALIBRATION"
    OTHER = "OTHER"


class MaintenanceRequestSourceType(StrEnum):
    MANUAL = "MANUAL"
    MOBILE = "MOBILE"
    SENSOR = "SENSOR"
    INSPECTION = "INSPECTION"
    CHECKLIST_FINDING = "CHECKLIST_FINDING"
    SYSTEM = "SYSTEM"


class MaintenanceRequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    TRIAGE = "TRIAGE"
    WAITING_INFORMATION = "WAITING_INFORMATION"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONVERTED_TO_WORK_ORDER = "CONVERTED_TO_WORK_ORDER"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class MaintenanceType(StrEnum):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    PREDICTIVE = "PREDICTIVE"
    CONDITION_BASED = "CONDITION_BASED"
    BREAKDOWN = "BREAKDOWN"
    EMERGENCY = "EMERGENCY"
    INSPECTION = "INSPECTION"
    CALIBRATION = "CALIBRATION"
    OVERHAUL = "OVERHAUL"
    IMPROVEMENT = "IMPROVEMENT"


class WorkOrderExecutionMode(StrEnum):
    INTERNAL = "INTERNAL"
    VENDOR = "VENDOR"
    HYBRID = "HYBRID"


class MaintenanceWorkOrderStatus(StrEnum):
    DRAFT = "DRAFT"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPROVED = "APPROVED"
    PLANNED = "PLANNED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    ON_HOLD = "ON_HOLD"
    WAITING_PART = "WAITING_PART"
    WAITING_VENDOR = "WAITING_VENDOR"
    COMPLETED = "COMPLETED"
    VERIFICATION = "VERIFICATION"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class MaintenanceRequestWorkOrderRelationshipType(StrEnum):
    PRIMARY = "PRIMARY"
    COMBINED = "COMBINED"
    FOLLOW_UP = "FOLLOW_UP"
    DIAGNOSTIC = "DIAGNOSTIC"
    PART_REPLACEMENT = "PART_REPLACEMENT"


class WorkOrderAssignmentRole(StrEnum):
    SUPERVISOR = "SUPERVISOR"
    LEAD_TECHNICIAN = "LEAD_TECHNICIAN"
    TECHNICIAN = "TECHNICIAN"
    INSPECTOR = "INSPECTOR"
    HELPER = "HELPER"


class MaintenanceTeamType(StrEnum):
    MECHANICAL = "MECHANICAL"
    ELECTRICAL = "ELECTRICAL"
    INSTRUMENTATION = "INSTRUMENTATION"
    IT = "IT"
    FACILITY = "FACILITY"
    VEHICLE = "VEHICLE"
    GENERAL = "GENERAL"
    MIXED = "MIXED"


class MaintenanceTeamMemberRole(StrEnum):
    SUPERVISOR = "SUPERVISOR"
    PLANNER = "PLANNER"
    LEAD_TECHNICIAN = "LEAD_TECHNICIAN"
    TECHNICIAN = "TECHNICIAN"
    INSPECTOR = "INSPECTOR"
    HELPER = "HELPER"


class MaintenanceScheduleSource(StrEnum):
    MANUAL = "MANUAL"
    REQUEST = "REQUEST"
    PREVENTIVE_PLAN = "PREVENTIVE_PLAN"
    METER_TRIGGER = "METER_TRIGGER"
    CONDITION_TRIGGER = "CONDITION_TRIGGER"
    VENDOR_VISIT = "VENDOR_VISIT"
    FOLLOW_UP = "FOLLOW_UP"


class MaintenanceScheduleStatus(StrEnum):
    PLANNED = "PLANNED"
    CONFIRMED = "CONFIRMED"
    DISPATCHED = "DISPATCHED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    MISSED = "MISSED"
    POSTPONED = "POSTPONED"
    CANCELLED = "CANCELLED"


class MaintenancePlanTriggerType(StrEnum):
    CALENDAR = "CALENDAR"
    METER = "METER"
    CALENDAR_OR_METER = "CALENDAR_OR_METER"
    CALENDAR_AND_METER = "CALENDAR_AND_METER"
    CONDITION = "CONDITION"
    MANUAL = "MANUAL"


class ChecklistResponseType(StrEnum):
    PASS_FAIL = "PASS_FAIL"
    YES_NO = "YES_NO"
    NUMERIC = "NUMERIC"
    TEXT = "TEXT"
    PHOTO = "PHOTO"
    MULTI_SELECT = "MULTI_SELECT"
    METER_READING = "METER_READING"


class ChecklistFailureResponseRule(StrEnum):
    NONE = "NONE"
    CREATE_FINDING = "CREATE_FINDING"
    REQUIRES_FOLLOW_UP = "REQUIRES_FOLLOW_UP"
    REQUIRES_ASSET_SHUTDOWN = "REQUIRES_ASSET_SHUTDOWN"


class ChecklistExecutionStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ChecklistOverallResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"


class ChecklistResultStatus(StrEnum):
    NORMAL = "NORMAL"
    ABNORMAL = "ABNORMAL"
    PASS = "PASS"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"


class MaintenanceFindingType(StrEnum):
    FAILURE = "FAILURE"
    DEFECT = "DEFECT"
    ABNORMAL_CONDITION = "ABNORMAL_CONDITION"
    SAFETY_RISK = "SAFETY_RISK"
    PART_WEAR = "PART_WEAR"
    PART_REPLACEMENT = "PART_REPLACEMENT"
    FURTHER_INSPECTION = "FURTHER_INSPECTION"
    ADJUSTMENT = "ADJUSTMENT"
    HOUSEKEEPING = "HOUSEKEEPING"
    DOCUMENTATION = "DOCUMENTATION"


class MaintenanceFindingSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class MaintenanceFindingStatus(StrEnum):
    OPEN = "OPEN"
    FOLLOW_UP_CREATED = "FOLLOW_UP_CREATED"
    RESOLVED = "RESOLVED"
    CANCELLED = "CANCELLED"


class MaintenancePartUsageType(StrEnum):
    ISSUE = "ISSUE"
    INSTALL = "INSTALL"
    REPLACE = "REPLACE"
    CONSUME = "CONSUME"
    RETURN = "RETURN"
    SCRAP = "SCRAP"


class MaintenanceLaborActivityType(StrEnum):
    INSPECTION = "INSPECTION"
    REPAIR = "REPAIR"
    REPLACEMENT = "REPLACEMENT"
    TESTING = "TESTING"
    CLEANUP = "CLEANUP"
    TRAVEL = "TRAVEL"
    WAITING = "WAITING"
    OTHER = "OTHER"
